#!/usr/bin/env python

def configure (ctx):
	ctx.check_cfg(
		package = 'glib-2.0',
		args = ['--cflags', '--libs'],
		mandatory = True
	)

	ctx.check_cfg(
		package = 'gmodule-2.0',
		args = ['--cflags', '--libs'],
		mandatory = True
	)

	ctx.check_cfg(
		package = 'libnm_glib',
		args = ['--cflags', '--libs'],
		atleast_version = '0.7.0'
	)

	ctx.find_program('grep', var = 'GREP')
	ctx.find_program('sed', var = 'SED')
	ctx.find_program('sort', var = 'SORT')

def build (ctx):
	if ctx.env.HAVE_LIBNM_GLIB:
		ctx.shlib(
			source = ['nm.c'],
			target = 'nm',
			use = ['GLIB-2.0', 'GMODULE-2.0', 'LIBNM_GLIB'],
			includes = ['.', '..'],
			install_path = '${LIBDIR}/sushi/maki/plugins'
		)
