#!/usr/bin/env python

def configure (ctx):
	ctx.check_cfg(
		package = 'glib-2.0',
		args = ['--cflags', '--libs'],
		uselib_store = 'GLIB'
	)

	ctx.check_cfg(
		package = 'gio-2.0',
		args = ['--cflags', '--libs'],
		atleast_version = '2.26',
		uselib_store = 'GIO'
	)

	ctx.check_cfg(
		package = 'gmodule-2.0',
		args = ['--cflags', '--libs'],
		uselib_store = 'GMODULE'
	)

	ctx.check_cfg(
		package = 'gupnp-igd-1.0',
		args = ['--cflags', '--libs'],
		uselib_store = 'GUPNP_IGD',
		mandatory = False
	)

def build (ctx):
	ctx.shlib(
		source = ['sleep.c'],
		target = 'sleep',
		use = ['GLIB', 'GIO', 'GMODULE'],
		includes = ['.', '..'],
		install_path = '${LIBDIR}/sushi/maki/plugins'
	)

	if ctx.env.HAVE_GUPNP_IGD:
		ctx.shlib(
			source = ['upnp.c'],
			target = 'upnp',
			use = ['GLIB', 'GMODULE', 'GUPNP_IGD'],
			includes = ['.', '..'],
			install_path = '${LIBDIR}/sushi/maki/plugins'
		)
