#!/usr/bin/env python

import os
import subprocess

def configure (conf):
	conf.check_tool('misc')

	p = subprocess.Popen(['pkg-config', '--variable', 'session_bus_services_dir', 'dbus-1'], stdout=subprocess.PIPE, close_fds=True)
	v = p.communicate()[0].strip()

	conf.env.DBUSDIR = v

	if not conf.env.VERSION:
		conf.env.VERSION = ''

def build (bld):
	if bld.env.DBUSDIR and bld.env.DBUSDIR.startswith(bld.env.PREFIX):
		bld.new_task_gen(
			features = 'subst',
			source = 'de.ikkoku.sushi.service.in',
			target = 'de.ikkoku.sushi.service',
			install_path = '${DBUSDIR}'
		)

	for man in ('maki.1', 'sushi-remote.1'):
		# FIXME gzip
		bld.new_task_gen(
			features = 'subst',
			source = '%s.in' % (man),
			target = man,
			install_path = '${MANDIR}/man1',
			dict = {'SUSHI_VERSION': bld.env.VERSION}
		)

	bld.install_files('${DATAROOTDIR}/sushi/maki', 'dbus.xml')
