#!/usr/bin/env python

def configure (ctx):
	ctx.find_program('gzip', var = 'GZIP')

	ctx.check_cfg(
		package = 'dbus-1',
		uselib_store = 'DBUS',
		variables = ['session_bus_services_dir']
	)

	if not ctx.env.VERSION:
		ctx.env.VERSION = ''

def build (ctx):
	ctx.install_files('${DATAROOTDIR}/sushi/maki', 'dbus.xml')

	dbus_dir = ctx.env.DBUS_session_bus_services_dir

	if dbus_dir and dbus_dir.startswith(ctx.env.PREFIX):
		ctx(
			features = 'subst',
			source = 'de.ikkoku.sushi.service.in',
			target = 'de.ikkoku.sushi.service',
			install_path = '${DBUS_session_bus_services_dir}'
		)

	for man in ('maki.1', 'sushi-remote.1'):
		ctx(
			features = 'subst',
			source = '%s.in' % (man),
			target = man,
			install_path = None,
			SUSHI_VERSION = ctx.env.VERSION
		)

	ctx.add_group()

	for man in ('maki.1', 'sushi-remote.1'):
		ctx(
			source = man,
			target = '%s.gz' % (man),
			rule = '${GZIP} -c ${SRC} > ${TGT}',
			install_path = '${MANDIR}/man1'
		)
