#!/usr/bin/env python

"""
Copyright (c) 2008-2009 Michael Kuhn
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
"""

import os
import socket
import subprocess
from xdg.BaseDirectory import xdg_config_home

if len(os.sys.argv) > 1:
	if os.sys.argv[1] == '--print-bus-address':
		try:
			f = open(os.path.join(xdg_config_home, 'sushi', 'bus_address'), 'r')
		except:
			print >> os.sys.stderr, 'Bus address could not be read.'
			os.sys.exit(1)

		print f.read()
		f.close()
		os.sys.exit(0)

if len(os.sys.argv) < 3:
	print >> os.sys.stderr, 'Usage: %s [user@]host command ...' % os.sys.argv[0]
	print >> os.sys.stderr, '       %s --print-bus-address' % os.sys.argv[0]
	os.sys.exit(1)

userhost = os.sys.argv[1]

command = []

if userhost != 'localhost':
	command.append('ssh')
	command.append(userhost)

command.append('sushi-remote')
command.append('--print-bus-address')

p = subprocess.Popen(command, stdout=subprocess.PIPE, close_fds=True)

bus_address = p.communicate()[0].strip()

if not bus_address:
	print >> os.sys.stderr, 'Bus address could not be determined.'
	os.sys.exit(1)

if not bus_address.startswith('tcp:'):
	print >> os.sys.stderr, 'Bus address has wrong format.'
	os.sys.exit(1)

bus_address = bus_address[4:].split(',')
port = 0

for i in range(len(bus_address)):
	if bus_address[i].startswith('host='):
		bus_address[i] = 'host=localhost'
	elif bus_address[i].startswith('port='):
		port = int(bus_address[i][5:])

if port == 0:
	print >> os.sys.stderr, 'Port could not be determined.'
	os.sys.exit(1)

try:
	s = socket.socket()
	s.connect(('localhost', port))
	s.close()
except:
	command = []
	command.append('ssh')
	command.append('-N')
	command.append('-f')
	command.append('-L')
	command.append('localhost:%d:localhost:%d' % (port, port))
	command.append(userhost)

	p = subprocess.Popen(command, close_fds=True)
	p.wait()

os.putenv('SUSHI_REMOTE_BUS_ADDRESS', 'tcp:%s' % ','.join(bus_address))

command = []

for i in range(2, len(os.sys.argv)):
	command.append(os.sys.argv[i])

p = subprocess.Popen(command, stdout=os.sys.stdout, stderr=os.sys.stderr, close_fds=True)
p.wait()
