#!/usr/bin/env python

from waflib import Utils

def configure (ctx):
	ctx.check_cfg(
		package = 'glib-2.0',
		args = ['--cflags', '--libs'],
		atleast_version = '2.20'
	)

	ctx.check_cfg(
		package = 'gio-2.0',
		args = ['--cflags', '--libs'],
		atleast_version = '2.26'
	)

	ctx.check_cfg(
		package = 'gobject-2.0',
		args = ['--cflags', '--libs']
	)

	ctx.check_cfg(
		package = 'gthread-2.0',
		args = ['--cflags', '--libs']
	)

	ctx.check_cfg(
		package = 'gmodule-2.0',
		args = ['--cflags', '--libs']
	)

	ctx.check_cfg(
		package = 'nice',
		args = ['--cflags', '--libs'],
		mandatory = False
	)

	ctx.find_program('grep', var = 'GREP')
	ctx.find_program('sed', var = 'SED')
	ctx.find_program('sort', var = 'SORT')

	if not ctx.env.VERSION:
		ctx.env.VERSION = ''

	ctx.define('SUSHI_VERSION', ctx.env.VERSION)

	ctx.write_config_header('config.h')

	ctx.recurse('plugins')

def build (ctx):
	components = ('ilib', 'sashimi', 'channel', 'channel_user', 'dcc_send', 'dbus', 'dbus_server', 'in', 'instance', 'log', 'maki', 'misc', 'network', 'out', 'plugin', 'server', 'user')

	ctx.program(
		source = ['%s.c' % (c) for c in components],
		target = 'maki',
		use = ['GLIB-2.0', 'GIO-2.0', 'GOBJECT-2.0', 'GTHREAD-2.0', 'GMODULE-2.0', 'NICE'],
		includes = ['.'],
		defines = ['MAKI_PLUGIN_DIRECTORY="%s"' % (Utils.subst_vars('${LIBDIR}/sushi/maki/plugins', ctx.env)),
			'MAKI_SHARE_DIRECTORY="%s"' % (Utils.subst_vars('${DATAROOTDIR}/sushi/maki', ctx.env))]
	)

	ctx.program(
		source = 'sushi-remote.c',
		target = 'sushi-remote',
		use = ['GLIB-2.0']
	)

	ctx.recurse('plugins')
