#!/usr/bin/env python

def configure (ctx):
	pass

def build (ctx):
	ctx.install_files('${DOCDIR}', ctx.path.ant_glob('*.txt'))
	ctx.install_files('${DOCDIR}/clients', ctx.path.ant_glob('clients/*.txt'))
	ctx.install_files('${DOCDIR}/irc', ctx.path.ant_glob('irc/*.txt'))
	ctx.install_files('${DOCDIR}/os', ctx.path.ant_glob('os/*.txt'))
